name: Atualizar README e Menus

on:
  push:
    paths:
      - '**/*'
  pull_request:
    paths:
      - '**/*'
  create:


jobs:
  update-readme-and-menus:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v2

      - name: Configurar Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14'

      - name: Instalar dependências
        run: npm install

      - name: Atualizar README e Menus
        run: node updateReadme.js

      - name: Commitar e fazer push se houver mudanças
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add . # Adiciona todas as alterações ao staging
          git diff --staged --quiet || git commit -m "Atualização automática do README e Menus" # Faz commit se houver mudanças
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
